-- MySQL Script generated by MySQL Workbench
-- Mon May 25 11:43:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema odontosys
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema odontosys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `odontosys` DEFAULT CHARACTER SET utf8 ;
USE `odontosys` ;

-- -----------------------------------------------------
-- Table `odontosys`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontosys`.`tipo_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `odontosys`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontosys`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipo_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idusuario_UNIQUE` (`id` ASC),
  INDEX `fk_usuario_tipo_usuario1_idx` (`tipo_usuario_id` ASC),
  CONSTRAINT `fk_usuario_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `odontosys`.`tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `odontosys`.`tipo_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontosys`.`tipo_funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idfuncionario_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `odontosys`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontosys`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(25) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `tipo_funcionario_id` INT NOT NULL,
  `cro` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idfuncionario_UNIQUE` (`id` ASC),
  INDEX `fk_funcionario_tipo_funcionario1_idx` (`tipo_funcionario_id` ASC),
  CONSTRAINT `fk_funcionario_tipo_funcionario1`
    FOREIGN KEY (`tipo_funcionario_id`)
    REFERENCES `odontosys`.`tipo_funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `odontosys`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontosys`.`paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_cadastro` DATE NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `rg` VARCHAR(10) NOT NULL,
  `cep` VARCHAR(15) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `rua` VARCHAR(50) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(25) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `observacao` VARCHAR(150) NOT NULL,
  `descricao_consulta` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idpaciente_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `odontosys`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontosys`.`consulta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_agendamento` DATE NOT NULL,
  `hora_agendamento` TIME NOT NULL,
  `observacao` VARCHAR(150) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `paciente_id` INT NOT NULL,
  `funcionario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_consulta_UNIQUE` (`id` ASC) ,
  INDEX `fk_consulta_paciente1_idx` (`paciente_id` ASC) ,
  INDEX `fk_consulta_funcionario1_idx` (`funcionario_id` ASC) ,
  CONSTRAINT `fk_consulta_paciente1`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `odontosys`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `odontosys`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `odontosys`.`prontuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontosys`.`prontuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_cadastro` DATE NOT NULL,
  `hora_cadastro` TIME NOT NULL,
  `observacao_receita` VARCHAR(150) NOT NULL,
  `observacao_atestado` VARCHAR(150) NOT NULL,
  `observacao_anamnese` VARCHAR(150) NOT NULL,
  `paciente_id_paciente` INT NOT NULL,
  `funcionario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_prontuario_UNIQUE` (`id` ASC) ,
  INDEX `fk_prontuario_paciente1_idx` (`paciente_id_paciente` ASC) ,
  INDEX `fk_prontuario_funcionario1_idx` (`funcionario_id` ASC) ,
  CONSTRAINT `fk_prontuario_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `odontosys`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prontuario_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `odontosys`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE `events` (
  `id` int(11) NOT NULL,
  `title` varchar(220) DEFAULT NULL,
  `color` varchar(10) DEFAULT NULL,
  `start` datetime DEFAULT NULL,
  `end` datetime DEFAULT NULL,
  `descricao` varchar(255) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Índices de tabelas apagadas
--

--
-- Índices de tabela `events`
--
ALTER TABLE `events`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de tabelas apagadas
--

--
-- AUTO_INCREMENT de tabela `events`
--
ALTER TABLE `events`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO tipo_usuario (id, nome) VALUES
(1, 'Dentista'),
(2, 'Funcionario');

INSERT INTO tipo_funcionario (id, nome) VALUES
(1, 'Dentista'),
(2, 'Atendente'),
(3, 'Tecnico de TI'),
(4, 'Zelador'),
(5, 'Supervisor'),
(6, 'Auxiliar'),
(7, 'Secretario');

INSERT INTO usuario (id, login, senha, tipo_usuario_id) VALUES (1, 'admin', 'admin', 2);
